# Template Dockerfile for using Tensorflow with the GPU. Install more dependencies and run more commands as needed
FROM nvidia/cuda:10.0-runtime-ubuntu18.04
LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"

# The commands below install Cuda and libcudnn in order for the code to run on the GPU
ENV CUDNN_VERSION 7.5.0.56
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
  libcudnn7=$CUDNN_VERSION-1+cuda10.0 && \
  apt-mark hold libcudnn7 && \
  rm -rf /var/lib/apt/lists/*


# Install python dependencies
RUN apt-get update && apt-get install -y \
  locales \
  python3 \
  python3-pip \
  wget \
  pkg-config \
  && python3 -m pip install pip==19.0.3 \
  Pillow \
  pytest \
  # fastapi dependencies
  fastapi[all] \
  # project dependencies
  numpy \
  # To use GPU:
  tensorflow-gpu
  # To use CPU instead :
  # tensorflow



# Set the locale (required for uvicorn)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 


WORKDIR /tensorflow_object_segmentation/src
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "5000"]