# Template Dockerfile for using Tensorflow with the GPU. Install more dependencies and run more commands as needed
#   Note: When running the Docker container, nvidia-docker has to be installed on your computer, and use the argument --runtime=nvidia in the docker run command, e.g.:
#   $ docker run --runtime=nvidia --rm -p <port_of_your_choice>:5000 <tag_name>

FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

# Install OS packages, adding the repo for python3.6

RUN apt-get update && \
  apt-get install -y software-properties-common && \
  add-apt-repository ppa:deadsnakes/ppa && \
  apt-get update
  
RUN apt-get install -y \
  locales \
  python3.6 \
  python3.6-dev \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*


RUN python3.6 -m pip install \
  Pillow \
  pytest \
  # fastapi dependencies
  fastapi[all] \
  # project dependencies
  numpy \
  # To use GPU:
  tensorflow-gpu
  # To use CPU instead:
  # tensorflow


# Set the locale (required for click, a dependency of FastAPI, on ubuntu 16/18)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

# Run the app
WORKDIR /app
CMD uvicorn main:app --host 0.0.0.0 --port 5000
