# Template Dockerfile for using Tensorflow with the GPU. Install more dependencies and run more commands as needed
#   Note: When running the Docker container, nvidia-docker has to be installed on your computer, and use the argument --runtime=nvidia in the docker run command, e.g.:
#   $ docker run --runtime=nvidia --rm -p <port_of_your_choice>:5000 <tag_name>

FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

# Install OS packages
RUN apt-get update --no-install-recommends && apt-get install -y \
  locales \
  python3 \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN python3 -m pip install \
  Pillow \
  pytest \
  # fastapi dependencies
  fastapi[all] \
  # project dependencies
  numpy \
  # To use GPU:
  tensorflow-gpu
  # To use CPU instead:
  # tensorflow

# Set the locale (required for click, a dependency of FastAPI, on ubuntu 18)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

# Copy the app code into the image
ADD ./app $HOME/app

# Run the app
WORKDIR /app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]